### PR TITLE
fixed issue while forgetting networks with SSID having spaces

### PR DESCRIPTION
**Pull request by hrithiksawhney**
## **Description**
Fixed issue while forgetting networks with SSID having spaces.

## **Related Issue**
https://github.com/TanmayPatil105/wifi-cli/issues/19

### CODE REVIEW

**Comment by TanmayPatil105** [comment]
@youpong Can you review it?

**Comment by youpong** [comment]
Yes. Assign me as a reviewer.

**Comment by TanmayPatil105** [comment]
Not sure why I am unable to add you as a reviewer!

**Review by youpong — APPROVED** [review]

**Comment by youpong** [comment]
@TanmayPatil105 merge it please.

**Pull request merged**
