### PR TITLE
fixed wifi connecting to an already connected network-ssid

### PR DESCRIPTION
**Pull request by hrithiksawhney**
## **Description**
Fixed wifi connecting to an already connected network-ssid.

## **Related Issue**
https://github.com/TanmayPatil105/wifi-cli/issues/21

### CODE REVIEW

**Comment by TanmayPatil105** [comment]
`nmcli -g name con show --active` shows all the services running.
In my case there are services running too!
Screenshot from 2022-10-24 13-58-34

**Comment by TanmayPatil105** [comment]
This still wouldn't work with Networks having more than 1 string in there `SSID`.

**Comment by TanmayPatil105** [comment]
Try looking at the `wifi list` function for reference!

**Comment by hrithiksawhney** [comment]
Hi @TanmayPatil105 ,
I checked the `command_list` function but I could not get why the added change will not work with networks having spaces. Can you please explain in detail?

**Pull request merged**
